### ISSUE TITLE
Wrong filtering of best found configuration

### ISSUE THREAD

**Issue by jhmenke** [kevinzakka/hypersearch#3]
hyperband.py, line 165:

`best_idx = np.argmax([b[1] for b in best_configs])`

Shouldn't it be 

`best_idx = np.argmin([b[1] for b in best_configs])`

as the value with the lowest loss is the best one? val_loss is also filtered by argmin beforehand

**Comment by kevinzakka** [comment]
@jhmenke absolutely right, I still have a few bugs to iron out, thanks for catching this one.
